# Generated by Django 4.2.3 on 2023-07-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_user_posts'),
        ('posts', '0012_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
