# Generated by Django 4.2.3 on 2023-07-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_posts',
        ),
    ]
