# Generated by Django 4.2.3 on 2023-07-16 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 11, 33, 41, 976229), null=True),
        ),
    ]
