# Generated by Django 4.2.3 on 2023-07-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user_posts_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_posts',
        ),
    ]
